# Generated by Django 5.0.6 on 2024-06-02 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='Dirección de envío')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('cuidados', models.TextField(verbose_name='Descripción de cuidados')),
                ('imagen_principal', models.ImageField(upload_to='productos/', verbose_name='Imagen Principal')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto 2')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto 3')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto 4')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], max_length=20, verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Druids.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Druids.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Druids.usuario'),
        ),
    ]
