# Generated by Django 5.0.6 on 2024-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(default='ApellidoTemporal', max_length=100, verbose_name='Apellido del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='EmailTemporal', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(default='NombreTemporal', max_length=100, verbose_name='Nombre del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='rut',
            field=models.CharField(default='RutTemporal', max_length=10, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
