# Generated by Django 5.0.6 on 2024-06-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0002_mensajecontacto_remove_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Arboles', 'Arboles'), ('Arbustos', 'Arbustos'), ('Cactus', 'Cactus'), ('Flores', 'Flores'), ('Implementos', 'Implementos'), ('Cuidados', 'Cuidados'), ('Enredaderas', 'Enredaderas')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Druids.producto')),
            ],
        ),
    ]
