# Generated by Django 5.0.6 on 2024-06-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0003_alter_producto_categoria_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Druids.pedido'),
        ),
    ]
