# Generated by Django 5.0.6 on 2024-06-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0006_usuario_usuario_alter_usuario_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='clave',
        ),
    ]
