# Generated by Django 5.0.6 on 2024-06-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0007_rename_contraseña_usuario_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
    ]
