# Generated by Django 5.0.6 on 2024-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0008_remove_usuario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto de perfil'),
        ),
    ]
