# Generated by Django 5.0.6 on 2024-07-05 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Druids', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cuidados',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de cuidados'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
